
############################
# Vars
############################
variable "aws_region" {
  description = "AWS region to deploy to"
  type        = string
  default     = "us-east-1"
}

variable "github_token" {
  type      = string
  sensitive = true
}

variable "article_blacklist_strings" {
  type      = string
  sensitive = true
}

variable "python_runtime" {
  default = "python3.12"
}

variable "openai_api_key" {
  type      = string
  sensitive = true
}

variable "anthropic_api_key" {
  type      = string
  sensitive = true
}

variable "cloudflare_api_token" {
  type      = string
  sensitive = true
}

variable "cloudflare_account_id" {
  description = "Cloudflare account ID"
  type        = string
}

variable "static_redirect_domains" {
  description = "Domains that redirect to homepage only (no path preservation)"
  type        = list(string)
  default     = []
}

variable "no_redirect_domains" {
  description = "Domains that should NOT redirect (primary sites, not aliases)"
  type        = list(string)
  default     = []
}

variable "all_domains" {
  description = "All domains we own in Cloudflare"
  type        = list(string)
  default     = []
}

variable "google_verification_tokens" {
  description = "Map of domain -> Google Site Verification token (generated by scripts/fetch_verification_tokens.py)"
  type        = map(string)
  default     = {}
  # Not sensitive - these tokens become public DNS TXT records anyway
}
