name: Create Folder from Variable

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Name of the folder to create'
        required: true
        type: string

jobs:
  create-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create folder
        run: |
          mkdir -p "${{ github.event.inputs.folder_name }}"
          touch "${{ github.event.inputs.folder_name }}/.keep"
          echo "Created folder: ${{ github.event.inputs.folder_name }}"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "${{ github.event.inputs.folder_name }}"
          git add "${{ github.event.inputs.folder_name }}"
          git commit -m "Add folder ${{ github.event.inputs.folder_name }}"
          git push
